### ISSUE TITLE
Running the same backtest twice produces different results

### ISSUE THREAD

**Issue by TheWalterWhite** [AbenezerMamo/crypto-signal#125]
Title says it all, clicking begin twice with the same settings gives a different final profit every time. Tested with both bittrex and binance.

**Comment by jrbartola** [comment]
This is expected behavior. Historical data get's grabbed from each exchange in the form of  [candlesticks](https://www.investopedia.com/terms/c/candlestick.asp). The goal of backtesting is to be able to emulate live trading with a particular strategy as accurately as possible. When trading on live data a bot will usually poll an exchange and get the latest price every time a predetermined time interval goes by (30 minutes, 1 hour, 1 day, etc.). The thing is, a live bot isn't always going to poll the exchange at the same price as the opening, closing, high or low for a particular candlestick-- it is more of a stochastic process. To make the simulation as accurately as possible, we sample a random price between the high and the low of each candlestick and use that as our data for backtesting. There is a bit of randomness involved, so no two runs are likely to output the same profit, buy points, or sell points. [This file](https://github.com/AbenezerMamo/crypto-signal/blob/master/app/behaviours/ui/backtesting/strategy.py#L36) contains the logic associated with the backtesting engine. Hope that makes sense.
