### ISSUE TITLE
Idea for communication

### ISSUE THREAD

**Issue by Bird-NZ** [AbenezerMamo/crypto-signal#157]
Hi, How about we start a closed discord or telegram group for this work. Would be good to get more of a community around this development and enable questions and ideas to flow better. Also I feel that this will bring out more question & ideas that people may feel able to ask in a less formal forum also will allow the group to offer answers to questions rather then just 2-3 leaders. - Then the Git can be a more formal tool around the code itself and workflow. Thoughts?

**Comment by rados10** [comment]
I like it!

**Comment by shads2** [comment]
Over the last month or so of development, myself and @jrbartola have learned a few things that require us to take stock of where we are at and what the next best thing for the project is. We are meeting this weekend to chat about it.

I've been thinking for quite some time it would be good to build a community aspect to the project and would love to foster that. We just want to be certain that we are building the right thing to form a community around.

I will keep this open and give an update early next week :)

**Comment by Bird-NZ** [comment]
Thanks for your sprite of openness to where the process thinking is, I do really appreciate that. To add my 10 cents of encouragement to this, I'd be saddened if this work stopped entirely but I understand and encourage that often there is a need to pivot on an idea or concept.

I feel like we at just at the start of something here that an interesting and diverse community could evolve from. Thx again, Mat.

**Comment by shads2** [comment]
Just to be clear we do not intend to stop development. We may just be re-adjusting the scope and intent so that we can be excellent at a particular job instead of being mediocre at several :)

**Comment by shads2** [comment]
Myself and @jrbartola caught up today and have made some solid decisions on what we intend to do moving forward.

First thing we are going to be doing is removing the bot and the UI behaviours from the project. Over the coming months we'll be providing that functionality in a different format but it won't be a part of this project. There are three primary reasons for this...
1. It feels like a bunch of very different projects slammed together.
2. Turning the trade bot into something genuinely useful requires more time and computational power than is reasonable for your average PC.
3. The current structure provides an acceptable user experience but the development experience is currently very poor, which is a side effect of problem 1 and 2.

Second thing is we will be doubling down on the default behaviour to turn it into a more useful trading assistant. We believe this to be the most widely used and useful component of the project but it hasn't seen the love it deserves and we want to fix that.

Last of all, we will be starting a community slack / discord / something in the coming week or two once we feel like we have sufficiently got the house in order. I'll update this issue and the Readme once that has happened.

**Comment by Bird-NZ** [comment]
Sounds great to me team, looking forward to being involved.

**Comment by jrbartola** [comment]
Hi all,

@shads2 and I have opened a [Discord channel](https://discordapp.com/invite/mn98mZ) to harbor a community around this project. Feel free to share this with anybody who is interesting in crypto-signal and its development!

**Comment by shads2** [comment]
And with the discord opened I am closing this issue :)

**Comment by cgmckeever** [comment]
@shads2 I like the idea of separating this into explicit projects. Is it too large of an ask to break this completely out as a data aggregator and then everything else can just be built on top of the database? Such as the entire analyzer is removed from the data aggregator peice?

This would make it super versatile and very useful to people even outside this project?

**Comment by shads2** [comment]
It wouldn't be useful to the average user. The amount of data it generates means you need to be running a reasonably sized instance on AWS, GCP or some other hosting provider and if you already have that level of technical knowledge... you probably already have the technical knowledge required to write the ingestor, it's very, very simple.

Once you move past data ingestion into the territory of the other component you begin to hit bigger problems. To make automated trade worth while you actually need _vast_ amounts of computing because predicting the future with any degree of reliability is actually kind of resource intensive. It would cost an individual _way more_ in computation than they would likely make from the automation.

We could easily provide something terrible that could potentially function in an up trending market and then throw your money out a window in a down trending market... but humans can already do that just fine themselves and I don't want to be responsible for providing that kind of shitty behaviour as software.

We do intend to continue working towards something useful for everyone, but simple restructures to the code are not enough to make it useful, it would just become a costly disappointment.

**Comment by cgmckeever** [comment]
You'd be surprised by how many people are looking for an easy data ingestor/aggregator, but I totally see what you are saying -- and appreciate the response. 

With that, to be clear - once you re-tool the project. It will doing the data ingesting and continue to add the later of dynamic trade assisting? Not 100% clear what the overall vision is now with the new direction.

Thanks!

**Comment by shads2** [comment]
For this current project, we aim to make it the best possible assistant we can to manual traders. We intend to keep it lightweight and highly targeted to that use case. 

Myself and @jrbartola are starting work on a new project for the automated trade assistant, but I can't give too many details yet because honestly we haven't 100% nailed down how everything is going to work yet.
