### ISSUE TITLE
secret.json

### ISSUE THREAD

**Issue by nimraMalik** [AbenezerMamo/crypto-signal#20]
where is that secret.json file??
where can i get BITTREX_API_KEY,BITTREX_SECRET,TWILIO_API_KEY,TWILIO_SECRET??
{
    "bittrex_key" : "BITTREX_API_KEY",
    "bittrex_secret" : "BITTREX_SECRET",
    "twilio_key": "TWILIO_API_KEY",
    "twilio_secret": "TWILIO_SECRET",
    "twilio_number": "TWILIO_PHONE_NUMBER",
    "my_number": "YOUR_PHONE_NUMBER"
}

**Comment by Satoshinaire** [comment]
@nimraMalik As the README says, you need to create it:

> Add a secrets.json file to the root directory of your project.

You just copy and paste the text you've copy and pasted above into a new file in the base directory of the project, and then swap the example values for your actual details.

**Comment by nimraMalik** [comment]
ok thankyou so much.
One more question is how can i get twilio key and secret??

**Comment by AbenezerMamo** [comment]
@nimraMalik You'll have to sign up for a Twilio account and get your own API Keys. You'll have to pay for a phone number and per text sent. Not very expensive since the number is a $1 a month and each text costs pennies. If you'd like to not pay for that, you can just hook it upto Slack or something
