### ISSUE TITLE
Feature Request: Trailing Stop Losses

### ISSUE THREAD

**Issue by AbenezerMamo** [AbenezerMamo/crypto-signal#49]
Writing feature requests and then connecting them to Github Project cards. This one is for creating stop losses within the bot.

**Context**:
When entering a position into a coin that's increasing in BTC value, it's hard to not ride the "FOMO" wave and stay in the position for too long.

In some instances, some coins pump really hard and dump with a 50% correction. Being apart of the pump is great - not so much for the dump. This is where stop losses can come in.

**Example Use Case:**
Imagine you entered a BTC/NEO position at 630k sats and it started increasing to 650k sats. The price will go up and down, so it's best to make sure we leave the position if it gets below 640k sats. Maybe based on previous supports (this can be inferred with Ichmoku Cloud), we can determine that 637k is the best price to leave the position so we're not being prematurely stopped out.

To break that down, imagine the following variables over time

- Start
Trade: BTC/NEO
Entry Position: 650k sats
Initial Stop Loss (5%): 617.5k sats

- Increase by 5% from original entry
Current Position: 682.5k sats
Current Stop Loss (2.5%): 665.435 sats

- Decrease by 2% from previous position
Current Position: 668.85
Current Stop Loss (taken from previous b/c of drop): 665.435 sats

At this point, we should hold the stop loss to be valid so we're still taking a profit. If we want to re-enter the position, we can enter again at a certain percentage above our previous stop loss (to make sure it's not a fake pump)

The goal of trailing stop losses is to let you lock in your gains instead of just riding the wave like a normal investor #bagolding

**Rules:**
- Initial stop loss should be 5% below initial Entry Position
- As price begins to move up, the trailing stop loss should be 2.5% below the current position
- Based on how fast the price action is happening, the trailing stop loss can be dynamic +- 1.5%

**Significance:**
It's difficult to predict price movements in crypto but it's easy to ride the waves, as long as you're able to enter and leave cleanly. Beyond any trading strategy, knowing when to leave a trade before a major loss occurs is critical.

Share feedback/thoughts/questions below!

**Comment by Andreilys** [comment]
I think the rule of "Initial stop loss should be 5% below initial Entry Position" would close out a lot of positions just due to the nature of volatility in crypto. Often times even if a coin goes up 100% in a day, it may drop 10% in one minute before going up another 30%. I see what you're trying to get at though, basically just ride the pumps and hope that they outweigh the losses you would get from positions closing early. Either way might be something to backtest to see how effective this would be, since if the gains outweigh the early stop outs then it might be worthwhile.

Another thing to consider is how effective this strategy would be in a bull vs bear market.

**Comment by shads2** [comment]
This issue is no longer relevant to this project
