### ISSUE TITLE
Wrong period is taken for all indicators

### ISSUE THREAD

**Issue by arbiro** [AbenezerMamo/crypto-signal#96]
Indicators should use last period_count ticks, instead they use the first period_count ticks that can be taken from historical_data. This is the case at least for bittrex.

**Comment by shads2** [comment]
I'll look into this further, this was a bug we had earlier on, though I thought this was well and truly resolved.

**Comment by arbiro** [comment]
It might have been fixed in the meantime and I have an old revision!? Even fixed(last prediction_count values from historical data) the calculated RSI for example does not match 1D one on bittrex or tradeview using bittrex data :(.

**Comment by shads2** [comment]
The current master does not appear to have this problem, the candlestick data time stamps are all correct.

All of the calculations for RSI and many other TA techniques were also replaced around the same time that the time stamp bug was fixed. Most TA techniques now use a more reliable library built for traditional stock trade instead of our own implementation.

**Comment by cgmckeever** [comment]
piggy backing on this. When watching XRP/BTC, TRX/BTC, GAS/BTC (Binance)
the RSI appears to be +/- 5 in comparison to TradingView.

Not sure if its related, was just trying to resolve this difference

**Comment by shads2** [comment]
So here is an information dump about where we are at:

There is a fundamental difference between what we do and what TradingView do that needs to be taken into account. We only get data for a single exchange where as TradingView aggregate across multiple exchanges. Even so when looking at single exchanges there are often differences.

My current theory is that TradingView do their own aggregation on much smaller candlestick time frames which means that TradingView may have up to an extra 23+ hours of data in their analysis. We use the daily aggregate sticks that exchanges provide, this is a limitation of dealing with on-demand queries as most exchanges do not provide 24 hours of small time frame candles.

Under the hood we use an open-source library called TA-Lib (https://www.ta-lib.org/) which has been around since 1999 and has been used in open source for trade analysis for a long time. That's not to say a bug doesn't exist, however given how long it has been around and in use I feel reasonably comfortable trusting it. We did try other solutions but this seemed to provide the best data.

At some point it would be great to have some one from a math heavy profession helping out with the project to validate that all of the maths is behaving the way we expect, but until we find one we test things to the best of our ability but ultimately have to trust that the tools available to us are performing correctly.

**Comment by IceBearZero** [comment]
@shads2 Thanks for the update! All that makes sense. I ran across your project while playing around with my own .. and needless to say, building your own RSI is painful without the other factors you mentioned involved!

Thanks!

**Comment by arbiro** [comment]
Afaik Tradingview only uses data from selected source( you can select
bittrex BTCUSDT or poloniex for example and it will only use that). I must
have an old version as the implementation in the one I'm using is a custom
one.

**Comment by shads2** [comment]
So I've taken some time over the last week to prod and poke at various things and as far as I am able to tell, everything works the way it is intended to work for the current master. For me to do anything further I would need something specific with detail as to how and why it is incorrect. 

For the moment I am closing this issue.
